config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :addresses
    resources :invitations, only: [:index, :new, :create, :destroy]
  end
  namespace :address do
    resources :verifications, except: [:index] do
      get '/', on: :collection, to: 'verifications#new'
    end
    resources :submissions, except: [:index] do
      post 'process_login', on: :collection, to: 'submissions#process_login'
      get '/', on: :collection, to: 'submissions#login'
      get 'success', on: :collection, to: 'submissions#success'
    end
  end

  get 'visitors/index'

  resources :addresses
  devise_for :users

  scope :webhooks do
    post 'postcards', to: 'webhooks#postcards'
  end

  get '/verify', to: 'address/verifications#new'

  root to: 'visitors#index'
end

app/models/address.rb
class Address < ApplicationRecord
  before_create :set_verification_code
  after_create :send_postcard

  
  private

  def set_verification_code
    self.verification_code = loop do
      haiku = Haikunator.haikunate
      break haiku unless Address.exists?(verification_code: haiku)
    end
  end

  def send_postcard
    postcard = LOB.postcards.create(
      description: description,
      to: {
        name: name,
        company: company,
        address_line1: line1,
        address_line2: line2,
        address_city: city,
        address_state: state,
        address_zip: zip
      },
      from: {
        company: ENV['POSTCARD_COMPANY_NAME'],
        address_line1: ENV['POSTCARD_ADDRESS_LINE1'],
        address_line2: ENV['POSTCARD_ADDRESS_LINE2'],
        address_city: ENV['POSTCARD_ADDRESS_CITY'],
        address_state: ENV['POSTCARD_ADDRESS_STATE'],
        address_zip: ENV['POSTCARD_ADDRESS_ZIP']
      },
      front: "https://consensus.zachapps.com/uploads/document/file/2/AddressVerificationCardFront.pdf",
      message: "Hello #{self.name},\nYour verification code is:\n#{self.verification_code}\n\nPlease visit:\naddress.zdnenterprises.com/verify\nto finish creating your account."
    )
    self.update(postcard_id: postcard['id'])
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  has_secure_token :access_code
  def verified_address
    Address.find_by(id: used_by)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def active?
    address && address.try(:verified?)
  end
end

app/controllers/address/submissions_controller.rb
class Address::SubmissionsController < ApplicationController
  before_action :set_invite, only: [:new, :create]
  def login
    @login = LoginToVerify.new
  end

  def process_login
    @outcome = LoginToVerify.run(login_params)
    unless @outcome.result == false
      session['invite_id'] = @outcome.result
      set_invite
      unless @invite.used?
        redirect_to new_address_submission_url
      else
        session.delete(:invite_id)
        redirect_to address_submissions_url, notice: 'Sorry, this access code has already been used.'
      end
    end
  end

  def new
    redirect_to address_submissions_url unless session['invite_id']
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      @invite.update(used: true, used_by: @address.id)
      session.delete(:invite_id)
      redirect_to success_address_submissions_url, notice: 'Expect a postcard to arrive within 5 days.'
    end
  end

  def success
    
  end

  private

  def set_invite
    @invite = Invitation.find(session['invite_id'])
  end

  def login_params
    params.require(:login_to_verify).permit(:access_code)
  end

  def address_params
    params.require(:address).permit(:name, :company, :line1, :line2, :city, :state, :zip, :phone, :email)
  end
end

app/controllers/address/verifications_controller.rb
class Address::VerificationsController < ApplicationController
  def new
    @verification = VerifyWithHaiku.new
  end

  def create
    @verification = VerifyWithHaiku.run(verification_params)
    if @verification.valid?
      redirect_to root_url, notice: 'Thanks! Your address has been verified!'
    else
      render :new
    end
  end


  private

  def verification_params
    params.require(:verify_with_haiku).permit(:verification_code)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /addresses
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  def create
    @address = Address.new(address_params)

    if @address.save
      redirect_to @address, notice: 'Address was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /addresses/1
  def update
    if @address.update(address_params)
      redirect_to @address, notice: 'Address was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /addresses/1
  def destroy
    @address.destroy
    redirect_to admin_addresses_url, notice: 'Address was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def address_params
      params.require(:address).permit(:line1, :line2, :city, :state, :zip, :email, :phone, :verified)
    end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @invitations = Invitation.all
  end

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new
    if @invitation.save
      redirect_to admin_invitations_url, notice: "NEW INVITE CODE: #{@invitation.access_code}"
    else
      redirect_to admin_invitations_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  def postcards
    data = JSON.parse request.body.read
    if @address = Address.find_by(postcard_id: data['body']['id'])
      @address.update(webhook_data: data)
      render json: { message: 'Webhook processed.' }, status: 200
    else
      render json: { message: 'Corresponding address not found.', status: 404 }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/address/submissions/login.html.slim
.container
  p.lead Please enter your access code:
  = simple_form_for @login, url: process_login_address_submissions_path, method: :post do |f|
    = f.input :access_code
    = f.submit 'Proceed', class: 'btn btn-primary'

app/views/address/submissions/new.html.slim
.container
  h1 Address::Submissions#new
  = simple_form_for @address, url: address_submissions_url do |f|
    = f.input :name, label: 'Your name'
    = f.input :company
    = f.input :line1, label: 'Address Line 1'
    = f.input :line2, label: 'Address Line 2'
    = f.input :city
    = f.input :state
    = f.input :zip
    = f.input :phone
    = f.submit 'Submit for Verification', class: 'btn btn-success'
  p Invite ID: #{session['invite_id']}

app/views/address/submissions/success.html.slim
h1 Success!
p.lead Your address verification request has been successfully submitted.
p Please allow 4-7 days for your verification code to arrive via USPS.

app/views/address/verifications/new.html.slim
.container
  = simple_form_for @verification, url: address_verifications_path do |f|
    = f.input :verification_code, 
      label: 'Enter your verification code as it appears on the postcard'
    = f.submit 'Verify', class: 'btn btn-success'

app/views/admin/addresses/_form.html.slim
= simple_form_for(@address) do |f|
  = f.error_notification

  .form-inputs
    = f.input :line1
    = f.input :line2
    = f.input :city
    = f.input :state
    = f.input :zip
    = f.input :email
    = f.input :phone
    = f.input :verified

  .form-actions
    = f.button :submit

app/views/admin/addresses/edit.html.slim
h1 Editing address

== render 'form'

= link_to 'Show', @address
'  |
= link_to 'Back', addresses_path

app/views/admin/addresses/index.html.slim
.container
  h2 Listing addresses

  table.table
    thead
      tr
        th Line1
        th Line2
        th City
        th State
        th Zip
        th Email
        th Phone
        th Verified
        th
        th
        th

    tbody
      - @addresses.each do |address|
        tr
          td = address.line1
          td = address.line2
          td = address.city
          td = address.state
          td = address.zip
          td = address.email
          td = address.phone
          td = address.verified
          td = link_to 'Show', [:admin, address]
          td = link_to 'Edit', edit_admin_address_path(address)
          td = link_to 'Destroy',[:admin, address], data: { confirm: 'Are you sure?' }, method: :delete

  br

app/views/admin/addresses/new.html.slim
h1 New address

== render 'form'

= link_to 'Back', addresses_path

app/views/admin/addresses/show.html.slim
p#notice = notice

p
  strong Line1:
  = @address.line1
p
  strong Line2:
  = @address.line2
p
  strong City:
  = @address.city
p
  strong State:
  = @address.state
p
  strong Zip:
  = @address.zip
p
  strong Email:
  = @address.email
p
  strong Phone:
  = @address.phone
p
  strong Verified:
  = @address.verified

= link_to 'Edit', edit_address_path(@address)
'  |
= link_to 'Back', addresses_path

app/views/admin/invitations/index.html.slim
.container
  h2 Invite Codes
  h3 &mdash; Unused Codes
  table.table
    thead
      tr
        th Created at
        th Access Code
    tbody
      - @invitations.where(used: false).each do |unused|
        tr
          td = unused.created_at
          td = unused.access_code
  h3 &mdash; Used Codes
  table.table
    thead
      tr
        th Created at
        th Access Code
        th Used by
    tbody
      - @invitations.where(used: true).each do |unused|
        tr
          td = unused.created_at
          td = unused.access_code
          td =  "Address #{unused.verified_address.try(:id)}"

app/views/admin/invitations/new.html.slim
.container
  = simple_form_for @invitation, url: admin_invitations_path do |f|
    = f.submit 'Generate Code', class: 'btn btn-primary'

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  
  <div class="container"><h1>ZDN Enterprises, LLC.</h1>
  <hr/><h2 class="text-muted float-right">Address Verification Service</h2></div>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/visitors/index.html.slim
.container
  p.lead Please choose from the following options:
  .btn-group
    = link_to 'Verify a new address', address_submissions_path, class: 'btn btn-primary btn-lg'
    = link_to 'I received my verification code in the mail',
      address_verifications_path, 
      class: 'btn btn-success btn-lg'